spring:
  datasource:
    url: jdbc:h2:~/fiapmusicabatch;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  batch:
    schema: classpath:schema-all.sql
    initialize-schema: always

file:
  musica: /Users/fabiomiyasato/Documents/musica.txt
  chunk: musica.csv
